#!/bin/zsh
# Wikify by Mario "Kuroir" Ricalde (@kuroir)
function wikify() {
  # Resolve where we should get the subjects.
  if [[ "$@" != "" ]]; then;
    subjects=( $@ );
  else;
    subjects=( . );
  fi;

  # Empty Home.md
  echo "Removing Home.md"
  home_file="$subjects/Home.md"
  rm $home_file

  for subject in $(ls -l $subjects | egrep '^d' | awk '{ print $9}'); do;
    directory="$subjects/$subject"
    if [[ "$directory" =~ "assets$" ]]; then
      continue
    fi
    file="$directory.md"
    echo "Processing Directory: $subject"

    ## Generate Table of Contents
    toc=$(ls -l $directory | awk ' NF >= 7 {
        if( ! match($9, /(sidebar|header|footer)/) ) {
          sub(/.*\//, "", $9);
          sub(/\.md$/, "", $9);
          gsub(/\-/, " ", $9);
          path=$9;
          gsub(/^[0-9]*\.\s+/, "", $9);
          printf("0. [[%s\|%s]]%s\n", $9, path, ($5 == 0) ? " ⚑" : "");
        } 
      }')

    sub=${subject//-/ }
    subject_title="\n### [[☰|$sub]] $sub ";

    # Write Root File (Smaller Index)
    echo "    Writing Index to $file";
    echo $toc > $file

    ## Add to the sidebar.
    sidebar_file="$directory/_sidebar.md"
    echo "    Writing Index to $sidebar_file";
    echo "$subject_title\n---" > $sidebar_file
    echo $toc >> $sidebar_file

    # Append to Home.md
    echo "    Writing Index to $home_file";
    echo $subject_title >> $home_file
    echo $toc >> $home_file

    # Add the files to Git
    git add $file
    git add $home_file
    git add $sidebar_file
  done
  echo "**Important**: The Tables of Content are generated. Any change will be overridden on the next update.<br>For more information: [GitHub Wikifier](https://github.com/kuroir/GitHub-Wikifier)" >> "$subjects/_footer.md"
  
}

wikify .
